serverAddr = "154.36.178.157"
serverPort = 7000

[auth]
method = "token"
token  = "classguruaipwd12262wenyz"

[[proxies]]
name       = "yp"
type       = "tcp"
localIP    = "127.0.0.1"
localPort  = 8790
remotePort = 12281

# Usage:
# 1. Make sure your payment service is running on http://localhost:8790
# 2. Run frpc: ./frpc -c 1.toml
# 3. Access via: https://yp.test.classguruai.com